### ISSUE TITLE
Reset phovea generator version

### ISSUE THREAD

**Issue by keckelt** [Caleydo/ordino_product#5]
TODO for the future: currently the phovea generator version is hardcoded by commit hash in the package.json of the touruíng branch

This should be changed back once a new generator version is released

**Comment by thinkh** [comment]
TODO should be also removed in the package.json in the `develop` branch.

**Comment by keckelt** [comment]
Removed the hardcoded generator version from `develop` and `touring`  branches.

**Comment by thinkh** [comment]
Just for reference: The related PR https://github.com/phovea/generator-phovea/pull/147 was merged into master.
